---
- name: Block inbound connections from specific IP on Windows
  hosts: "{{ host }}"
  vars:
    ansible_shell_type: powershell
  tasks:
    - name: Block inbound connections from specific IP
      community.windows.win_firewall_rule:
        name: "Block_{{ ip_addr }}"
        direction: In
        action: Block
        enabled: yes
        localip: any
        remoteip: "{{ ip_addr }}"
        localport: any
        remoteport: any
        protocol: any
      become: yes
