---
- name: Modify firewall
  hosts: labssh
  tasks:
  - name: Block specific IP
    ansible.builtin.iptables:
      chain: INPUT
      source: "{{ ip_addr }}"
      jump: DROP
    become: yes
  - name: Save iptables
    ansible.builtin.shell: /sbin/iptables-save > /etc/iptables/rules.v4
    become: yes
