---
- name: Block IP on Linux (persistent)
  hosts: "{{ host }}"
  tasks:
    - name: Block specific IP
      ansible.builtin.iptables:
        chain: INPUT
        source: "{{ ip_addr }}"
        jump: DROP
      become: yes
    - name: Save iptables rules
      ansible.builtin.shell:
        cmd: "iptables-save > /etc/iptables/rules.v4"
      become: yes
    - name: Restart iptables service
      ansible.builtin.systemd:
        name: iptables
        state: restarted

