---
- name: Modify service (persistent)
  hosts: "{{ host }}"
  tasks:
    - name: Modify whether service is allowed through external zone
      ansible.posix.firewalld:
        service: "{{ service }}"
        permanent: true
        state: "{{ enabled_or_disabled }}"
        zone: external
      become: yes
      
    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
      become: yes
