---
- name: Block IP on Linux (persistent)
  hosts: "{{ host }}"
  tasks:
    - name: Block specific IP
      ansible.posix.firewalld:
        source: "{{ ip_addr }}"
        permenant: yes
        zone: external
        state: disabled
      become: yes
