---
- name: Block IP on Linux (persistent)
  hosts: "{{ host }}"
  tasks:
    - name: Block specific IP
      ansible.posix.firewalld:
        source: "{{ ip_addr }}"
        permanent: yes
        zone: external
        state: disabled
      become: yes
      
    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
      become: yes
