---
- name: Allow service (persistent)
  hosts: "{{ host }}"
  tasks:
    - name: Allow service through external zone
      ansible.posix.firewalld:
        service: "{{ service }}"
        permanent: true
        state: enabled
        zone: external
      become: yes
      
    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
      become: yes
