---
- name: Deny by default
  hosts: "{{ host }}"
  tasks:
  - name: Allow SSH in the external zone
    ansible.posix.firewalld:
      service: ssh
      zone: external
      state: enabled
      immediate: yes
      permanent: true
    become: yes

  - name: Set default policy for external zone to drop
    ansible.posix.firewalld:
      zone: external
      state: enabled
      target: DROP
      permanent: true
    become: yes

  - name: Reload firewalld
  ansible.posix.firewalld:
    state: reloaded
  become: yes
