---
- name: Modify IP status on Linux (persistent)
  hosts: "{{ host }}"
  tasks:
    - name: Block/allow specific IP
      ansible.posix.firewalld:
        source: "{{ ip_addr }}"
        permanent: yes
        zone: external
        state: "{{ enabled_or_disabled }}"
      become: yes
      
    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
      become: yes
