---
- name: Modify IP status on Linux (persistent)
  hosts: "{{ host }}"
  tasks:
    - name: Block/allow specific IP
      ansible.posix.firewalld:
        source: "{{ ip_addr }}"
        permanent: yes
        zone: external
        state: "{{ enabled_or_disabled }}"
      become: yes
      
    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
      become: yes

    - name: Get active rules, send as debug
      ansible.builtin.shell: 
        cmd: firewall-cmd --zone=external --list-all
      register: output
      become: yes
  
    - name: Get debug info
      debug:
        var: output.stdout
