---
- name: Block IP on Linux (persistent)
  hosts: "{{ host }}"
  tasks:
    - name: Block specific IP
      ansible.posix.firewalld:
        rich_rule: 'rule family="ipv4" source address="{{ ip_address }}" drop'
        permenant: yes
        zone: external
        state: disabled
      become: yes
