---
- name: Pre-baking for linux firewall config with ansible
  hosts: "{{ host }}"
  tasks:
  - name: Install iptables-persistent
    ansible.builtin.package:
      name: iptables-persistent
      state: present
    become: yes
