---
- name: Pre-baking for linux firewall config with ansible
  hosts: "{{ host }}"
  tasks:
  
  - name: Install firewalld
    ansible.builtin.package:
      name: firewalld
      state: present
    become: yes

  - name: Start and enable firewalld
    ansible.builtin.service:
      name: firewalld
      state: started
      enabled: yes
    become: yes
    
  - name: Stop and disable iptables
    ansible.builtin.service:
      name: iptables
      state: stopped
      enabled: no
    become: yes
    ignore_errors: yes

  - name: Stop UFW
    command: ufw disable
    ignore_errors: yes
    become: yes

  - name: Disable UFW on startup
    ansible.builtin.lineinfile:
      path: /etc/ufw/ufw.conf
      regexp: '^ENABLED='
      line: 'ENABLED=no'
    ignore_errors: yes
    become: yes

  - name: Get active public network interface
    ansible.builtin.shell:
      cmd: "ip route get 1 | awk '{print $5;exit}'"
    register: active_interface
    become: yes

  - name: Set interface for external zone
    ansible.buitin.lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-{{ active_interface }}
      regexp: '^ZONE='
      line: 'ZONE=external'
    notify: Restart NetworkManager

  - name: Restart NetworkManager
    ansible.builtin.service:
      name: NetworkManager
      state: restarted
    become: yes
        
  - name: Reload firewalld
    ansible.builtin.service:
      name: firewalld
      state: reloaded
    become: yes



