---
- name: Pre-baking for linux firewall config with ansible
  hosts: "{{ host }}"
  tasks:
  
  - name: Install firewalld
    ansible.builtin.package:
      name: firewalld
      state: present
    become: yes

  - name: Start and enable firewalld
    ansible.builtin.systemd:
      name: firewalld
      state: started
      enabled: yes
    become: yes
    
  - name: Stop and disable iptables
    ansible.builtin.systemd:
      name: iptables
      state: stopped
      enabled: no
    become: yes
    ignore_errors: yes

  - name: Stop UFW
    command: ufw disable
    ignore_errors: yes
    become: yes

  - name: Disable UFW on startup
    lineinfile:
      path: /etc/ufw/ufw.conf
      regexp: '^ENABLED='
      line: 'ENABLED=no'
    ignore_errors: yes
    become: yes

  - name: Get active public network interface
    ansible.builtin.shell:
      cmd: "ip route get 1 | awk '{print $5;exit}'"
    register: active_interface
    become: yes

  - name: Add active interface to external zone in firewalld
    ansible.posix.firewalld:
      zone: external
      interface: "{{ active_interface.stdout }}"
      state: enabled
      permanent: yes
      immediate: yes
    become: yes

  - name: Allow SSH in the external zone
    ansible.posix.firewalld:
      service: ssh
      zone: external
      state: enabled
      immediate: yes
      permanent: true
    become: yes

  - name: Set default policy for external zone to drop
    ansible.posix.firewalld:
      zone: external
      state: enabled
      target: DROP
      permanent: true
    become: yes

