- name: Block IP on Linux (persistent)
  hosts: "{{ host }}"
  tasks:
  - name: Install iptables-persistent
    ansible.builtin.package:
      name: iptables-persistent
      state: present
    become: yes
