---
- name: Pre-baking for linux firewall config with ansible
  hosts: "{{ host }}"
  tasks:
  
  - name: Install firewalld
    ansible.builtin.package:
      name: firewalld
      state: present
    become: yes

  - name: Start and enable firewalld
    ansible.builtin.systemd:
      name: firewalld
      state: started
      enabled: yes
    become: yes
    
  - name: Stop and disable iptables
    ansible.builtin.systemd:
      name: iptables
      state: stopped
      enabled: no
    become: yes

    - name: Get active public network interface
      ansible.builtin.shell:
        cmd: "ip route get 1 | awk '{print $5;exit}'"
      register: active_interface
      become: yes

    - name: Add active interface to public zone in firewalld
      ansible.posix.firewalld:
        zone: public
        interface: "{{ active_interface.stdout }}"
        state: enabled
        permanent: yes
        immediate: yes
      become: yes
