---
- name: Reset firewalld configuration for external zone
  hosts: "{{ host }}"
  become: yes
  tasks:
    - name: Reset all sources in external zone
      firewalld:
        zone: external
        source: "{{ item }}"
        state: absent
      loop: "{{ lookup('community.general.firewalld', zone='external', sources=True) }}"

    - name: Reset all services in external zone
      ansible.posix.firewalld:
        zone: external
        service: "{{ item }}"
        state: absent
      loop: "{{ lookup('community.general.firewalld', zone='external', services=True) }}"

    - name: Reset all ports in external zone
      ansible.posix.firewalld:
        zone: external
        port: "{{ item.port }}/{{ item.protocol }}"
        state: absent
      loop: "{{ lookup('community.general.firewalld', zone='external', ports=True) }}"

    - name: Reset all protocols in external zone
      ansible.posix.firewalld:
        zone: external
        protocol: "{{ item }}"
        state: absent
      loop: "{{ lookup('community.general.firewalld', zone='external', protocols=True) }}"

    - name: Reset all forward ports in external zone
      ansible.posix.firewalld:
        zone: external
        forward_port: "{{ item }}"
        state: absent
      loop: "{{ lookup('community.general.firewalld', zone='external', forward_ports=True) }}"

    - name: Reset all ICMP blocks in external zone
      ansible.posix.firewalld:
        zone: external
        icmp_block: "{{ item }}"
        state: absent
      loop: "{{ lookup('community.general.firewalld', zone='external', icmp_blocks=True) }}"

    - name: Reset all rich rules in external zone
      ansible.posix.firewalld:
        zone: external
        rich_rule: "{{ item }}"
        state: absent
      loop: "{{ lookup('community.general.firewalld', zone='external', rich_rules=True) }}"
  
    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
    
    - name: Get active rules
      ansible.builtin.shell:
        cmd: firewall-cmd --zone=external --list-all
      register: active_rules

  
    - name: Get active zone
      ansible.builtin.shell:
        cmd: firewall-cmd --get-active-zone
      register: active_zone
  
    - name: Debug active rules, active zone, and default policy
      ansible.builtin.debug:
        msg:
          - "{{ active_rules.stdout }}"
          - "{{ active_zone.stdout }}"
