---
- name: Reset firewalld configuration for external zone
  hosts: all
  become: yes
  tasks:
    - name: Reset all sources in external zone
      firewalld:
        zone: external
        source: "{{ item }}"
        state: absent
      loop: "{{ lookup('community.general.firewalld', zone='external', sources=True) }}"

    - name: Reset all services in external zone
      firewalld:
        zone: external
        service: "{{ item }}"
        state: absent
      loop: "{{ lookup('community.general.firewalld', zone='external', services=True) }}"

    - name: Reset all ports in external zone
      firewalld:
        zone: external
        port: "{{ item.port }}/{{ item.protocol }}"
        state: absent
      loop: "{{ lookup('community.general.firewalld', zone='external', ports=True) }}"

    - name: Reset all protocols in external zone
      firewalld:
        zone: external
        protocol: "{{ item }}"
        state: absent
      loop: "{{ lookup('community.general.firewalld', zone='external', protocols=True) }}"

    - name: Reset all forward ports in external zone
      firewalld:
        zone: external
        forward_port: "{{ item }}"
        state: absent
      loop: "{{ lookup('community.general.firewalld', zone='external', forward_ports=True) }}"

    - name: Reset all ICMP blocks in external zone
      firewalld:
        zone: external
        icmp_block: "{{ item }}"
        state: absent
      loop: "{{ lookup('community.general.firewalld', zone='external', icmp_blocks=True) }}"

    - name: Reset all rich rules in external zone
      firewalld:
        zone: external
        rich_rule: "{{ item }}"
        state: absent
      loop: "{{ lookup('community.general.firewalld', zone='external', rich_rules=True) }}"
