---
- name: Get firewall external zone info
  hosts: "{{ host }}"
  tasks:
  - name: Get active rules
    ansible.builtin.shell:
      cmd: firewall-cmd --zone=external --list-all
    register: active_rules
    become: yes

  - name: Get active zone
    ansible.builtin.shell:
      cmd: firewall-cmd --get-active-zone
    register: active_zone
    become: yes

  - name: Debug active rules, active zone, and default policy
    ansible.builtin.debug:
      msg:
        - "{{ active_rules.stdout }}"
        - "{{ active_zone.stdout }}"
