---
- name: Quarantine
  hosts: "{{ host }}"
  become: yes
  tasks:
    - name: Wipe all existing outbound rules
      ansible.builtin.iptables:
        chain: OUTPUT
        state: absent
        
    - name: Allow outbound connections to the Ansible server on port 22
      ansible.builtin.iptables:
        chain: OUTPUT
        destination: "{{ ansible_server }}"
        protocol: tcp
        destination_port: 22
        jump: ACCEPT
        
    - name: Deny outbound connections to the LAN group
      ansible.builtin.iptables:
        chain: OUTPUT
        destination: "{{ lan_group }}"
        jump: DROP

    - name: Allow connections to any other hosts
      ansible.builtin.iptables:
        chain: OUTPUT
        jump: ACCEPT

    - name: Restart iptables service
      ansible.builtin.systemd:
        name: iptables
        state: restarted
