---
- name: Quarantine
  hosts: "{{ host }}"
  become: yes
  tasks:
  
    - name: Allow outbound traffic to essential IPs in the external zone
      ansible.posix.firewalld:
        rich_rule: "rule family='ipv4' source address='{{ item }}' accept"
        zone: external
        permanent: yes
        state: enabled
      loop: "{{ essential }}"

    - name: Block all outbound traffic to LAN group in the external zone
      ansible.posix.firewalld:
        source: "{{ item }}"
        zone: external
        state: enabled
        permanent: yes
      loop: "{{ LAN_group }}"
      
    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
      become: yes
